markdown: rdiscount
paginate: 4
paginate_files:
 - index.html
safe: false

permalink: /:year/:month/:day/:title.html

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
lsi: true

title :  紫梦莹轩
tagline: Happy Everyday
author :
  name : Cynthia Young
  email : cynthia.young0512@gmail.com
  github : young0512
  
archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html

sitemap_path: /sitemap.txt
RSS_path: /atom.xml

BASE_PATH : 
HOME_PATH : /
ASSET_PATH : /assets

production_url : http://young0512.github.com
